SELECT participants_person.Name, adjfeedback_adjudicatorfeedbackquestion.name "Frage", answer
FROM participants_adjudicator
INNER JOIN participants_person
ON participants_adjudicator.person_ptr_id=participants_person.id
INNER JOIN adjfeedback_adjudicatorfeedback
ON adjfeedback_adjudicatorfeedback.adjudicator_id=participants_adjudicator.person_ptr_id
INNER JOIN adjfeedback_adjudicatorfeedbackintegeranswer
ON adjfeedback_adjudicatorfeedbackintegeranswer.feedback_id=adjfeedback_adjudicatorfeedback.id
INNER JOIN adjfeedback_adjudicatorfeedbackquestion
ON adjfeedback_adjudicatorfeedbackquestion.id=adjfeedback_adjudicatorfeedbackintegeranswer.question_id
